package server

import (
	"log/slog"
	"net/http"
)

// registerWorkflowRoutes registers the daily dashboard, neighbor, and year flow.
func (s *Server) registerWorkflowRoutes(mux *http.ServeMux) {
	mux.Handle("GET /{$}", s.auth(s.handleDashboard))
	mux.Handle("GET /stats", s.auth(s.handleStats))
	mux.Handle("GET /stats/all", s.auth(s.handleStatsAll))
	mux.Handle("GET /neighbors/{id}", s.auth(s.handleNeighborDetail))
	mux.Handle("GET /neighbors/{id}/overview", s.auth(s.handleNeighborOverview))
	mux.Handle("GET /neighbors/{id}/overview.pdf", s.auth(s.handleNeighborOverviewPDF))
	mux.Handle("GET /neighbors", s.auth(s.handleNeighborsManage))
	mux.Handle("POST /neighbors/create", s.auth(s.handleNeighborManageCreate))
	mux.Handle("POST /neighbors/{id}/update", s.auth(s.handleNeighborUpdate))
	mux.Handle("POST /neighbors/{id}/archive", s.auth(s.handleNeighborArchive))
	mux.Handle("POST /neighbors/{id}/delete", s.auth(s.handleNeighborDelete))
	mux.Handle("POST /neighbors/{id}/anonymize", s.auth(s.handleNeighborAnonymize))
	mux.Handle("POST /years/add-neighbor", s.auth(s.handleYearAddNeighbor))
	mux.Handle("POST /years/remove-neighbor", s.auth(s.handleYearRemoveNeighbor))
	mux.Handle("POST /years/carry-over", s.auth(s.handleCarryOverNeighbors))
	mux.Handle("POST /years/mark-paid", s.auth(s.handleNeighborSettle))
	mux.Handle("GET /years/{id}/abschluss", s.auth(s.handleYearClosing))
	mux.Handle("GET /years/{id}/wechsel", s.auth(s.handleYearRollover))
	mux.Handle("POST /years/{id}/wechsel/create", s.auth(s.handleYearRolloverCreate))
	mux.Handle("POST /years/{id}/wechsel/neighbors", s.auth(s.handleYearRolloverNeighbors))
}

// registerDocumentRoutes registers receipts, invoices, and document delivery.
func (s *Server) registerDocumentRoutes(mux *http.ServeMux) {
	mux.Handle("GET /neighbors/{id}/beleg", s.auth(s.handleNeighborBeleg))
	mux.Handle("GET /neighbors/{id}/beleg.pdf", s.auth(s.handleBelegPDF))
	mux.Handle("POST /neighbors/{id}/beleg/email", s.auth(s.handleBelegEmail))
	mux.Handle("POST /neighbors/{id}/beleg/mark-sent", s.auth(s.handleBelegMarkSent))
	mux.Handle("POST /neighbors/{id}/beleg/unsend", s.auth(s.handleBelegUnsend))
	mux.Handle("POST /neighbors/{id}/beleg/share", s.auth(s.handleBelegShareCreate))
	mux.Handle("POST /neighbors/{id}/beleg/share/revoke", s.auth(s.handleBelegShareRevoke))
	mux.HandleFunc("GET /s/beleg/{token}", s.handleSharedBeleg)
	mux.HandleFunc("GET /s/portal/{token}", s.handleSharedBeleg)
	mux.HandleFunc("GET /s/portal/{token}/invoice.pdf", s.handleSharedInvoicePDF)
	mux.HandleFunc("POST /s/portal/{token}/feedback", s.handlePortalFeedback)
	mux.Handle("GET /years/{id}/issue-all", s.auth(s.handleBatchIssuePreview))
	mux.Handle("POST /years/{id}/issue-all", s.auth(s.handleBatchIssueCommit))
	mux.Handle("GET /neighbors/{id}/invoice/confirm", s.auth(s.handleInvoiceConfirm))
	mux.Handle("POST /neighbors/{id}/invoice", s.auth(s.handleInvoiceIssue))
	mux.Handle("POST /neighbors/{id}/invoice/storno", s.auth(s.handleInvoiceStorno))
	mux.Handle("POST /neighbors/{id}/invoice/gutschrift", s.auth(s.handleInvoiceGutschrift))
	mux.Handle("GET /neighbors/{id}/invoice/epc-qr.png", s.auth(s.handleInvoiceEpcQR))
	mux.Handle("GET /beleg/share-qr.png", s.auth(s.handleBelegShareQR))
	mux.Handle("POST /documents/{id}/storno", s.auth(s.handleDocumentStorno))
	mux.Handle("GET /documents/{id}/ebinterface.xml", s.auth(s.handleEInvoiceXML))
}

// registerBookingRoutes registers booking mutation, attachment, and list routes.
func (s *Server) registerBookingRoutes(mux *http.ServeMux) {
	mux.Handle("POST /entries", s.auth(s.handleEntryCreate))
	mux.Handle("POST /entries/quick", s.auth(s.handleQuickEntries))
	mux.Handle("GET /entries/{id}/edit", s.auth(s.handleEntryEditForm))
	mux.Handle("GET /entries/{id}/copy", s.auth(s.handleEntryCopy))
	mux.Handle("POST /entries/{id}/photos", s.auth(s.handleEntryPhotoUpload))
	mux.Handle("GET /entries/{id}/photos/{pid}", s.auth(s.handleEntryPhotoServe))
	mux.Handle("POST /entries/{id}/photos/{pid}/delete", s.auth(s.handleEntryPhotoDelete))
	mux.Handle("POST /entries/{id}/update", s.auth(s.handleEntryUpdate))
	mux.Handle("POST /entries/{id}/void", s.auth(s.handleEntryVoid))
	mux.Handle("POST /entries/{id}/delete", s.auth(s.handleEntryDelete))
	mux.Handle("POST /ledger/{id}/photos", s.auth(s.handleLedgerPhotoUpload))
	mux.Handle("GET /ledger/{id}/photos/{pid}", s.auth(s.handleLedgerPhotoServe))
	mux.Handle("POST /ledger/{id}/photos/{pid}/delete", s.auth(s.handleLedgerPhotoDelete))
	mux.Handle("POST /neighbors/{id}/ledger", s.auth(s.handleLedgerAdd))
	mux.Handle("GET /ledger/{id}/copy", s.auth(s.handleLedgerCopy))
	mux.Handle("GET /ledger/{id}/edit", s.auth(s.handleLedgerEditForm))
	mux.Handle("POST /ledger/{id}/update", s.auth(s.handleLedgerUpdate))
	mux.Handle("POST /ledger/{id}/void", s.auth(s.handleLedgerVoid))
	mux.Handle("POST /ledger/{id}/delete", s.auth(s.handleLedgerDelete))
	mux.Handle("POST /neighbors/{id}/payments", s.auth(s.handlePaymentAdd))
	mux.Handle("POST /neighbors/{id}/carry-forward", s.auth(s.handleNeighborCarryForward))
	mux.Handle("GET /payments/{id}/edit", s.auth(s.handlePaymentEditForm))
	mux.Handle("POST /payments/{id}/update", s.auth(s.handlePaymentUpdate))
	mux.Handle("GET /payments/{id}/copy", s.auth(s.handlePaymentCopy))
	mux.Handle("POST /payments/{id}/delete", s.auth(s.handlePaymentDelete))
	mux.Handle("POST /payments/{id}/restore", s.auth(s.handlePaymentRestore))
	mux.Handle("POST /neighbors/{id}/credit-payout", s.auth(s.handleCreditPayout))
	mux.Handle("POST /neighbors/{id}/gutschrift", s.auth(s.handleFreeGutschrift))
	mux.Handle("POST /neighbors/{id}/anzahlung", s.auth(s.handleAnzahlungCreate))
	mux.Handle("POST /neighbors/{id}/installments", s.auth(s.handleInstallmentAdd))
	mux.Handle("POST /installments/{id}/delete", s.auth(s.handleInstallmentDelete))
	mux.Handle("POST /neighbors/{id}/mannstunden", s.auth(s.handleMannstundenAdd))
	mux.Handle("POST /neighbors/{id}/anfahrt", s.auth(s.handleAnfahrtAdd))
	mux.Handle("GET /neighbors/{id}/recalc", s.auth(s.handleNeighborRecalcPreview))
	mux.Handle("POST /neighbors/{id}/recalc", s.auth(s.handleNeighborRecalcApply))
	mux.Handle("GET /years/{id}/recalc", s.auth(s.handleYearRecalcPreview))
	mux.Handle("POST /years/{id}/recalc", s.auth(s.handleYearRecalcApply))
	mux.Handle("GET /buchungen", s.auth(s.handleEntryList))
	mux.Handle("POST /buchungen/bulk", s.auth(s.handleEntryBulk))
	mux.Handle("POST /views/bookings", s.auth(s.handleSavedViewCreate))
	mux.Handle("POST /views/{id}/delete", s.auth(s.handleSavedViewDelete))
	mux.Handle("GET /stats/export.csv", s.auth(s.handleStatsExport))
	mux.Handle("GET /api/base/{id}/pricing", s.auth(s.handlePricingAPI))
	mux.Handle("GET /api/search", s.auth(s.handleSearchAPI))
	mux.Handle("GET /api/entries/precheck", s.auth(s.handleEntryPrecheck))
	mux.Handle("POST /recurring/{id}/update", s.auth(s.handleRecurringUpdate))
	mux.Handle("POST /recurring/{id}/run-now", s.auth(s.handleRecurringRunNow))
	mux.Handle("POST /recurring/{id}/skip-next", s.auth(s.handleRecurringSkipNext))
	mux.Handle("GET /personen", s.auth(s.handlePersons))
	mux.Handle("POST /personen", s.auth(s.handlePersonCreate))
	mux.Handle("POST /personen/{id}/update", s.auth(s.handlePersonUpdate))
	mux.Handle("POST /personen/{id}/archive", s.auth(s.handlePersonArchive))
	mux.Handle("POST /personen/{id}/delete", s.auth(s.handlePersonDelete))
	mux.Handle("GET /rechnungsjournal", s.auth(s.handleJournal))
	mux.Handle("GET /rechnungsjournal/export.csv", s.auth(s.handleJournalCSV))
	mux.Handle("GET /rechnungsjournal/buchhaltung.csv", s.auth(s.handleAccountingCSV))
	mux.Handle("POST /rechnungsjournal/profile", s.admin(s.handleAccountingProfileSave))
	mux.Handle("POST /rechnungsjournal/profile/{id}/delete", s.admin(s.handleAccountingProfileDelete))
	mux.Handle("GET /rechnungsjournal/archiv.zip", s.auth(s.handleJournalZip))
	mux.Handle("GET /rechnungsjournal/rechnungen.pdf", s.auth(s.handleJournalPDF))
}

func (s *Server) registerPublicRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /healthz", s.handleHealth)
	mux.HandleFunc("GET /readyz", s.handleHealth)
	mux.HandleFunc("GET /livez", s.handleLive)
	mux.HandleFunc("POST /csp-report", s.handleCSPReport)
	if len(s.cfg.MetricsToken) >= metricsTokenMinLen {
		mux.HandleFunc("GET /metrics", s.handleMetrics)
	} else if s.cfg.MetricsToken != "" {
		slog.Warn("METRICS_TOKEN is too short; /metrics stays disabled", "min_len", metricsTokenMinLen)
	}
	mux.Handle("GET /static/", http.StripPrefix("/static/", staticServer()))
	mux.HandleFunc("GET /theme", s.handleTheme)
	mux.HandleFunc("GET /manifest.webmanifest", s.handleManifest)
	mux.HandleFunc("GET /sw.js", s.handleServiceWorker)
	mux.HandleFunc("GET /offline", s.handleOffline)
	mux.HandleFunc("GET /login", s.handleLoginForm)
	mux.HandleFunc("POST /login", s.handleLogin)
	mux.HandleFunc("POST /login/2fa", s.handleLogin2FA)
	mux.HandleFunc("POST /login/passkey/begin", s.handlePasskeyLoginBegin)
	mux.HandleFunc("POST /login/passkey/finish", s.handlePasskeyLoginFinish)
	mux.HandleFunc("POST /logout", s.handleLogout)
}

func (s *Server) registerCatalogRoutes(mux *http.ServeMux) {
	mux.Handle("GET /prices", s.auth(s.handlePrices))
	mux.Handle("GET /prices/compare", s.auth(s.handlePriceCompare))
	mux.Handle("GET /prices/machines/labels", s.auth(s.handleMachineLabels))
	mux.Handle("GET /prices/machines/{id}/qr.png", s.auth(s.handleMachineQR))
	mux.Handle("GET /machines/{id}/book", s.auth(s.handleMachineBook))
	mux.Handle("POST /prices/loadlevels", s.auth(s.handleLoadLevelSave))
	mux.Handle("POST /prices/loadlevels/{id}/delete", s.auth(s.handleLoadLevelDelete))
	mux.Handle("POST /prices/fuel-adjustments", s.auth(s.handleFuelAdjustmentSave))
	mux.Handle("POST /prices/fuel-adjustments/{id}/delete", s.auth(s.handleFuelAdjustmentDelete))
	mux.Handle("POST /prices/tractors", s.auth(s.handleTractorSave))
	mux.Handle("POST /prices/tractors/{id}/toggle", s.auth(s.handleTractorToggle))
	mux.Handle("POST /prices/tractors/{id}/delete", s.auth(s.handleTractorDelete))
	mux.Handle("POST /prices/machines", s.auth(s.handleMachineSave))
	mux.Handle("POST /prices/machines/{id}/cost-model", s.auth(s.handleMachineCostModel))
	mux.Handle("POST /prices/machines/{id}/toggle", s.auth(s.handleMachineToggle))
	mux.Handle("POST /prices/machines/{id}/delete", s.auth(s.handleMachineDelete))
	mux.Handle("GET /gespanne", s.auth(s.handleGespanne))
	mux.Handle("POST /gespanne", s.auth(s.handleGespannSave))
	mux.Handle("POST /gespanne/{id}/delete", s.auth(s.handleGespannDelete))
	mux.Handle("GET /years", s.auth(s.handleYears))
	mux.Handle("POST /years", s.auth(s.handleYearCreate))
	mux.Handle("POST /years/{id}/status", s.auth(s.handleYearStatus))
	mux.Handle("POST /years/{id}/update", s.auth(s.handleYearUpdate))
	mux.Handle("POST /years/{id}/delete", s.auth(s.handleYearDelete))
	mux.Handle("GET /bases", s.auth(s.handleBases))
	mux.Handle("POST /bases", s.auth(s.handleBaseCreate))
	mux.Handle("POST /bases/{id}/update", s.auth(s.handleBaseUpdate))
	mux.Handle("POST /bases/{id}/delete", s.auth(s.handleBaseDelete))
	mux.Handle("POST /bases/{id}/lock", s.auth(s.handleBaseLock))
	mux.Handle("POST /bases/{id}/unlock", s.auth(s.handleBaseUnlock))
}

func (s *Server) registerAccountAndOperationsRoutes(mux *http.ServeMux) {
	mux.Handle("GET /profile", s.auth(s.handleProfile))
	mux.Handle("GET /notifications", s.auth(s.handleNotifications))
	mux.Handle("POST /notifications/{id}/open", s.auth(s.handleNotificationOpen))
	mux.Handle("POST /notifications/{id}/dismiss", s.auth(s.handleNotificationDismiss))
	mux.Handle("POST /notifications/read-all", s.auth(s.handleNotificationsReadAll))
	mux.Handle("POST /account/notifications", s.auth(s.handleNotificationPreferences))
	mux.Handle("GET /account/password", s.auth(s.handleAccountPasswordForm))
	mux.Handle("POST /account/password", s.auth(s.handleAccountPasswordSubmit))
	mux.Handle("GET /account/passkeys", s.auth(s.handlePasskeys))
	mux.Handle("POST /account/passkeys/register/begin", s.auth(s.handlePasskeyRegisterBegin))
	mux.Handle("POST /account/passkeys/register/finish", s.auth(s.handlePasskeyRegisterFinish))
	mux.Handle("POST /account/passkeys/{id}/delete", s.auth(s.handlePasskeyDelete))
	mux.Handle("GET /account/2fa", s.auth(s.handleTwoFactor))
	mux.Handle("GET /account/2fa/qr.png", s.auth(s.handleTwoFactorQR))
	mux.Handle("POST /account/2fa/confirm", s.auth(s.handleTwoFactorConfirm))
	mux.Handle("POST /account/2fa/recovery", s.auth(s.handleRecoveryRegenerate))
	mux.Handle("POST /account/2fa/disable", s.auth(s.handleTwoFactorDisable))
	mux.Handle("POST /account/sessions/revoke", s.auth(s.handleSessionRevoke))
	mux.Handle("POST /account/sessions/revoke-others", s.auth(s.handleSessionRevokeOthers))

	mux.Handle("GET /payments/import", s.auth(s.handlePaymentImportForm))
	mux.Handle("POST /payments/import/preview", s.auth(s.handlePaymentImportPreview))
	mux.Handle("POST /payments/import", s.auth(s.handlePaymentImportCommit))
	mux.Handle("GET /payments/import/batches/{id}", s.auth(s.handlePaymentImportBatch))
	mux.Handle("GET /payments/import/batches/{id}/report.csv", s.auth(s.handlePaymentImportReport))
	mux.Handle("POST /payments/import/rows/{id}/reverse", s.auth(s.handlePaymentImportReverse))
	mux.Handle("GET /recurring", s.auth(s.handleRecurringList))
	mux.Handle("GET /data-quality", s.auth(s.handleDataQuality))
	mux.Handle("POST /entries/{id}/recur", s.auth(s.handleRecurringCreate))
	mux.Handle("POST /ledger/{id}/recur", s.auth(s.handleLedgerRecurringCreate))
	mux.Handle("POST /recurring/{id}/toggle", s.auth(s.handleRecurringToggle))
	mux.Handle("POST /recurring/{id}/delete", s.auth(s.handleRecurringDelete))
	mux.Handle("GET /entries/import", s.auth(s.handleImportForm))
	mux.Handle("GET /entries/import/sample.csv", s.auth(s.handleImportSample))
	mux.Handle("POST /entries/import/preview", s.auth(s.handleImportPreview))
	mux.Handle("POST /entries/import", s.auth(s.handleImportCommit))
	mux.Handle("GET /export/year/{id}", s.auth(s.handleExportYear))
	mux.Handle("GET /export/neighbor/{id}", s.auth(s.handleExportNeighbor))
	mux.Handle("GET /neighbors/{id}/dsgvo-export.json", s.auth(s.handleNeighborDataExport))

	mux.Handle("GET /mahnwesen", s.auth(s.handleMahnwesen))
	mux.Handle("GET /mahnwesen/export.csv", s.auth(s.handleMahnwesenExport))
	mux.Handle("GET /neighbors/{id}/mahnung", s.auth(s.handleNeighborMahnung))
	mux.Handle("GET /neighbors/{id}/mahnung.pdf", s.auth(s.handleMahnungPDF))
	mux.Handle("POST /neighbors/{id}/mahnung/email", s.auth(s.handleMahnungEmail))
	mux.Handle("POST /neighbors/{id}/mahnung/mark-sent", s.auth(s.handleMahnungMarkSent))
	mux.Handle("POST /mahnwesen/batch-email", s.auth(s.handleMahnwesenBatchEmail))
	mux.Handle("GET /neighbors/{id}/mahnung/epc-qr.png", s.auth(s.handleMahnungEpcQR))
}

func (s *Server) registerAdminRoutes(mux *http.ServeMux) {
	mux.Handle("GET /admin/audit", s.admin(s.handleAudit))
	mux.Handle("GET /admin/audit/export", s.admin(s.handleAuditExport))
	mux.Handle("GET /admin/mail", s.admin(s.handleMailOutbox))
	mux.Handle("GET /admin/mail/{id}", s.admin(s.handleMailOutboxDetail))
	mux.Handle("POST /admin/mail/{id}/retry", s.admin(s.handleMailRetry))
	mux.Handle("POST /admin/mail/{id}/force-resend", s.admin(s.handleMailForceResend))
	mux.Handle("POST /admin/mail/{id}/release", s.admin(s.handleMailCenterRelease))
	mux.Handle("POST /admin/mail/{id}/discard", s.admin(s.handleMailCenterDiscard))
	mux.Handle("GET /admin/backup", s.admin(s.handleBackupStatus))
	mux.Handle("POST /admin/backup/run", s.admin(s.handleBackupRun))
	mux.Handle("POST /admin/backup/run-scheduled", s.admin(s.handleBackupRunScheduled))
	mux.Handle("POST /admin/backup/settings", s.admin(s.handleBackupSettings))
	mux.Handle("GET /admin/backup/file/{name}", s.admin(s.handleBackupFile))
	mux.Handle("POST /admin/backup/validate", s.admin(s.handleBackupValidate))
	mux.Handle("POST /admin/backup/restore", s.admin(s.handleBackupRestore))
	mux.Handle("POST /admin/backup/s3/test", s.admin(s.handleBackupS3Test))
	mux.Handle("POST /admin/backup/s3/run", s.admin(s.handleBackupS3Run))
	mux.Handle("GET /admin/backup/s3/file/{name}", s.admin(s.handleBackupS3File))
	mux.Handle("POST /admin/backup/held-mail/{id}/release", s.admin(s.handleHeldMailRelease))
	mux.Handle("POST /admin/backup/held-mail/{id}/discard", s.admin(s.handleHeldMailDiscard))
	mux.Handle("GET /admin/company", s.admin(s.handleCompany))
	mux.Handle("POST /admin/company", s.admin(s.handleCompanySave))
	mux.Handle("GET /admin/users", s.admin(s.handleUsers))
	mux.Handle("POST /admin/users", s.admin(s.handleUserCreate))
	mux.Handle("POST /admin/users/{id}/password", s.admin(s.handleUserPassword))
	mux.Handle("POST /admin/users/{id}/update", s.admin(s.handleUserUpdate))
	mux.Handle("POST /admin/users/{id}/role", s.admin(s.handleUserRole))
	mux.Handle("POST /admin/users/{id}/reset-2fa", s.admin(s.handleUserResetTotp))
	mux.Handle("POST /admin/users/{id}/delete", s.admin(s.handleUserDelete))
}
