-- Reusable equipment supplied by a neighbor. Financial bookings keep their own
-- JSON snapshots; this table is editable master data only.
CREATE TABLE neighbor_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    neighbor_id BIGINT NOT NULL REFERENCES neighbors(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    capacity NUMERIC(14,4) NOT NULL DEFAULT 0 CHECK (capacity >= 0),
    capacity_unit TEXT NOT NULL DEFAULT '' CHECK (char_length(capacity_unit) <= 16),
    billing_unit TEXT NOT NULL CHECK (char_length(billing_unit) BETWEEN 1 AND 16),
    default_rate NUMERIC(14,4) NOT NULL DEFAULT 0 CHECK (default_rate >= 0),
    note TEXT NOT NULL DEFAULT '' CHECK (char_length(note) <= 2000),
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((capacity = 0 AND capacity_unit = '') OR (capacity > 0 AND capacity_unit <> ''))
);

CREATE UNIQUE INDEX neighbor_equipment_neighbor_name_unique
    ON neighbor_equipment (neighbor_id, lower(name));
CREATE INDEX neighbor_equipment_neighbor_active_idx
    ON neighbor_equipment (neighbor_id, archived, name);
